#include "compressedsensing.hpp"
#include "cgsense.hpp"
#include "sense.hpp"
//#include "directmethod.hpp"
//#include "grappa.hpp"
#include "ktpoints.hpp"
//#include "nifty.hpp"
#include "nufft.hpp"
//#include "relativesensitivities.hpp"
//#include "spiral.hpp"
//#include "karb.hpp"
#ifdef HAVE_MPI
    #include "mpitest.hpp"
#endif
# include "dwt2test.hpp"
