#include "compressedsensing.hpp"
#include "cgsense.hpp"
#include "sense.hpp"
//#include "directmethod.hpp"
#include "grappa.hpp"
#include "ktpoints.hpp"
//#include "nifty.hpp"
#include "nufft.hpp"
//#include "relativesensitivities.hpp"
#ifndef _MSC_VER
  #include "spiral.hpp"
  #include "karb.hpp"
  #include "slicegrad.hpp"
#endif
#include "dummy.hpp"
