CXX=cl
CXXFLAGS=/openmp /nologo /EHsc /I..\.. /I..\..\.. /I.. /I..\..\..\misc /IC:\Intel\ComposerXE-2011\mkl\include "/IC:\Program Files\HDF_Group\HDF5\1.8.12\include" /IC:\local\boost_1_55_0 /I"C:\Program Files\MATLAB\R2013b\extern\include" /c 
LINK=link
LDFLAGS=/libpath:C:\Intel\ComposerXE-2011\mkl\lib\intel64 /libpath:"C:\Program Files\HDF_Group\HDF5\1.8.12\lib" /libpath:"C:\Program Files\MATLAB\R2013b\extern\lib\win64\microsoft"
LIBS=mkl_rt.lib hdf5.lib hdf5_cpp.lib libmx.lib libmat.lib
RM=del

all: t_hdf5.exe t_matlab.exe t_codeare.exe check

t_hdf5.exe: t_hdf5.cpp
	$(CXX) $(CXXFLAGS) t_hdf5.cpp 
	$(LINK) $(LDFLAGS) t_hdf5.obj $(LIBS)
t_matlab.exe: t_matlab.cpp
	$(CXX) $(CXXFLAGS) t_matlab.cpp 
	$(LINK) $(LDFLAGS) t_matlab.obj $(LIBS)
t_codeare.exe: t_codeare.cpp
	$(CXX) $(CXXFLAGS) t_codeare.cpp 
	$(LINK) $(LDFLAGS) t_codeare.obj $(LIBS)

check:
	t_hdf5.exe
	t_matlab.exe
	t_codeare.exe

clean: 
	$(RM) *.obj
	$(RM) *.exe