CXX=cl
CXXFLAGS=/openmp /nologo /EHsc /I..\.. /I..\..\.. /I.. /I..\..\io /I..\..\simd /I..\..\..\misc /IC:\local\boost_1_55_0 /I..\..\arithmetic /c /w
LINK=link
LDFLAGS=/libpath:C:\Intel\ComposerXE-2011\mkl\lib\intel64 /nologo
LIBS=mkl_rt.lib
RM=del

all: t_dwt.exe check

t_dwt.exe: t_dwt.cpp
	$(CXX) $(CXXFLAGS) t_dwt.cpp 
	$(LINK) $(LDFLAGS) t_dwt.obj $(LIBS)

check:
	t_dwt.exe

clean: 
	$(RM) *.obj
	$(RM) *.exe