CXX=cl
CXXFLAGS=/openmp /nologo /EHsc /I..\.. /I..\..\.. /I.. /I..\..\io /I..\..\simd /IC:\Intel\ComposerXE-2011\mkl\include /IC:\local\boost_1_55_0 /I..\..\arithmetic /c /w
LINK=link
LDFLAGS=/libpath:C:\Intel\ComposerXE-2011\mkl\lib\intel64 /nologo
LIBS=mkl_rt.lib
RM=del

all: t_chol.exe t_dot.exe  t_eig.exe  t_gemm.exe  t_gemv.exe  t_inv.exe  t_norm.exe  t_pinv.exe  t_svd.exe check

t_chol.exe: t_chol.cpp
	$(CXX) $(CXXFLAGS) t_chol.cpp 
	$(LINK) $(LDFLAGS) t_chol.obj $(LIBS)
t_dot.exe: t_dot.cpp
	$(CXX) $(CXXFLAGS) t_dot.cpp 
	$(LINK) $(LDFLAGS) t_dot.obj $(LIBS)
t_eig.exe: t_eig.cpp
	$(CXX) $(CXXFLAGS) t_eig.cpp 
	$(LINK) $(LDFLAGS) t_eig.obj $(LIBS)
t_gemm.exe: t_gemm.cpp
	$(CXX) $(CXXFLAGS) t_gemm.cpp 
	$(LINK) $(LDFLAGS) t_gemm.obj $(LIBS)
t_gemv.exe: t_gemv.cpp
	$(CXX) $(CXXFLAGS) t_gemv.cpp 
	$(LINK) $(LDFLAGS) t_gemv.obj $(LIBS)
t_inv.exe: t_inv.cpp
	$(CXX) $(CXXFLAGS) t_inv.cpp 
	$(LINK) $(LDFLAGS) t_inv.obj $(LIBS)
t_norm.exe: t_norm.cpp
	$(CXX) $(CXXFLAGS) t_norm.cpp 
	$(LINK) $(LDFLAGS) t_norm.obj $(LIBS)
t_pinv.exe: t_pinv.cpp
	$(CXX) $(CXXFLAGS) t_pinv.cpp 
	$(LINK) $(LDFLAGS) t_pinv.obj $(LIBS)
t_svd.exe: t_svd.cpp
	$(CXX) $(CXXFLAGS) t_svd.cpp 
	$(LINK) $(LDFLAGS) t_svd.obj $(LIBS)

check:
	t_chol.exe
	t_dot.exe
	t_eig.exe
	t_gemm.exe
	t_gemv.exe
	t_inv.exe
	t_norm.exe
	t_pinv.exe
	t_svd.exe

clean: 
	$(RM) *.obj
	$(RM) *.exe