CXX=cl
CXXFLAGS=/openmp /nologo /EHsc /I.. /I..\.. /I..\..\.. /I..\..\..\misc /I..\..\arithmetic /I..\..\..\tinyxml /I..\..\io /I..\..\linalg /I..\..\simd /IC:\Intel\ComposerXE-2011\mkl\include /IC:\local\boost_1_55_0 /IC:\local\fftw /IC:\local\openssl64\inc32 /c /w /DTIXML_USE_STL
LINK=link
LDFLAGS=/libpath:C:\Intel\ComposerXE-2011\mkl\lib\intel64 /libpath:C:\local\fftw /libpath:C:\local\openssl64
LIBS=mkl_rt.lib libfftw3-3.lib libfftw3f-3.lib libeay32.lib ssleay32.lib
RM=del

.SUFFIXES: .cpp .obj

all: t_dft.exe check

.cpp.exe:
	$(CXX) $(CXXFLAGS) $*.cpp
	$(LINK) $(LDFLAGS) $(LIBS) $*.obj

clean: 
	$(RM) *.obj
	$(RM) *.exe

check:
	t_dft.exe
