/*
 *  codeare Copyright (C) 2007-2010 Kaveh Vahedipour
 *                               Forschungszentrum Juelich, Germany
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
 *  02110-1301  USA
 */

#ifndef __RRS_MODULE_IDL__
#define __RRS_MODULE_IDL__

/**
 * @brief Remote recon service module
 */
module RRSModule {


	typedef sequence<float>  floats;   /*!< raw data real or imaginary repositories */
	typedef sequence<double> doubles;  /*!< helper data                             */
	typedef sequence<short>  shorts;   /*!< pixel data repositories                 */
	typedef sequence<long>   longs;    /*!< dimension reositories                   */


	/**
	 * @brief   Complex data
	 */
	struct      cxfl_data         {
		
		floats  vals;  /**< Data chain of real/imag */
		longs   dims;  /**< Dimesions     */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief   Complex double data
	 */
	struct      cxdb_data         {
		
		doubles vals;  /**< Data chain of real/imag */
		longs   dims;  /**< Dimesions     */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief   Real single data
	 */
	struct      rlfl_data       {

		floats  vals;  /**< Data      */
		longs   dims;  /**< Dimesions */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief   Real double data
	 */
	struct      rldb_data       {

		doubles vals;  /**< Data      */
		longs   dims;  /**< Dimesions */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief   Short integer data
	 */
	struct      shrt_data       {

		shorts  vals;  /**< Data      */
		longs   dims;  /**< Dimesions */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief   Long integer data
	 */
	struct      long_data       {

		longs   vals;  /**< Data      */
		longs   dims;  /**< Dimesions */
		floats  res;   /**< Resolution     */

	};


	/**
	 * @brief Remote recon service interface definition
	 */
	interface RRSInterface {
		
		/**
		 * @brief         Process data
		 *                Process data according to a particular method
		 *
		 * @param  name   Name of strategy
		 * @return        Status
		 */
		short        Process (in string name);
		
		/**
		 * @brief         Finalise
		 *                Clear data. Unload library.
		 *
		 * @param  name   Name of strategy
		 * @return        Status
		 */
		short        Finalise (in string name);
		
		/**
		 * @brief         Finalise
		 *                Clear data. Unload library.
		 *
		 * @param  name   Name of strategy
		 * @return        Status
		 */
		short       Prepare (in string name);
		
		/**
		 * @brief         Intialise
		 *                Initilise process library
		 *
		 * @param  name   Name of recontruction method
		 * @return        Status
		 */
		short       Init (in string name);

		/**
		 * @brief         Clear RAM
		 *                Clean up any left over objects and leave.
		 *
		 * @return        Status
		 */
		short       CleanUp ();

		/**
		 * @brief         Transport complex matrix from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_cxfl (in string name, inout cxfl_data data);

		
		/**
		 * @brief         Transport and announce complex matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_cxfl (in string name, in cxfl_data data);

		
		/**
		 * @brief         Transport complex matrix from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_cxdb (in string name, inout cxdb_data data);

		
		/**
		 * @brief         Transport and announce complex matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_cxdb (in string name, in cxdb_data data);

		
		/**
		 * @brief         Transport real matrix from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_rldb (in string name, inout rldb_data data);

		
		/**
		 * @brief         Transport and announce real matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_rldb (in string name, in rldb_data data);

		
		/**
		 * @brief         Transport real matrix from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_rlfl (in string name, inout rlfl_data data);

		
		/**
		 * @brief         Transport and announce real matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_rlfl (in string name, in rlfl_data data);

		
		/**
		 * @brief         Transport short integer matrix from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_shrt (in string name, inout shrt_data data);

		
		/**
		 * @brief         Transport and announce short integer matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_shrt (in string name, in shrt_data data);

		
		/**
		 * @brief         Transport short integer long from backend identified by ...
		 *
		 * @param  name   its name
		 * @param  data   Data matrix
		 */ 
		void              get_long (in string name, inout long_data data);

		
		/**
		 * @brief         Transport and announce long integer matrix to backend
		 *
		 * @param  name   Name
		 * @param  data   Data matrix
		 */ 
		void              set_long (in string name, in long_data data);

		
		/**
		 * @brief         Declare attributes labels and values.
		 */
		attribute         string       config;

		
	};
	
};

#endif
